/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    CardMangement: typeof import('./src/components/CardMangement.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChessBoard: typeof import('./src/components/ChessBoard.vue')['default']
    GameOptions: typeof import('./src/components/GameOptions.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
